services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
        - ./data/redis:/data
  sql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: demo
    volumes:
      - ./data/pg:/var/lib/postgresql/data